services:
  - type: web
    name: vocab-assist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn new_app:app
    envVars:
      - key: FLASK_ENV
        value: production
