services:
  - type: web
    name: vocab-assist
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: gunicorn --bind 0.0.0.0:$PORT new_app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5001
      - key: GEMINI_API_KEY
        value: AIzaSyDdlpRoOhsmj8KPWiX5krNFOfTCwSMj8LY
